# Generated by Django 4.2.4 on 2023-10-06 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_menu', models.CharField(max_length=10, unique=True)),
                ('nama_menu_lengkap', models.CharField(max_length=255)),
                ('nama_menu_singkat', models.CharField(max_length=50)),
                ('gambar_menu', models.ImageField(upload_to='menu_images/')),
                ('keterangan_menu', models.TextField()),
                ('status_aktif_menu', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='JenisSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_size', models.CharField(max_length=10, unique=True)),
                ('nama_size', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='KelompokMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_kelompok', models.CharField(max_length=10, unique=True)),
                ('nama_kelompok', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PenjualanDetail',
            fields=[
                ('nomor_nota_penjualan', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('harga_menu', models.DecimalField(decimal_places=2, max_digits=10)),
                ('harga_pokok', models.DecimalField(decimal_places=2, max_digits=10)),
                ('jumlah_harga', models.DecimalField(decimal_places=2, max_digits=10)),
                ('qty_menu', models.PositiveIntegerField()),
                ('kode_menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menuapp.datamenu')),
            ],
        ),
        migrations.CreateModel(
            name='JenisMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_jenis', models.CharField(max_length=10, unique=True)),
                ('nama_jenis', models.CharField(max_length=255)),
                ('kelompok_menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menuapp.kelompokmenu')),
            ],
        ),
        migrations.CreateModel(
            name='HargaMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('harga_menu', models.DecimalField(decimal_places=2, max_digits=10)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menuapp.datamenu')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menuapp.jenissize')),
            ],
        ),
        migrations.AddField(
            model_name='datamenu',
            name='jenis_menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menuapp.jenismenu'),
        ),
    ]
