# Generated by Django 4.2.4 on 2023-10-06 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menuapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='penjualandetail',
            name='harga_pokok',
        ),
    ]
