# Generated by Django 4.2.4 on 2023-10-29 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menuapp', '0002_bahanmenu'),
    ]

    operations = [
        migrations.AddField(
            model_name='bahanmenu',
            name='size',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='menuapp.jenissize'),
        ),
    ]
