# Generated by Django 4.2.4 on 2023-10-08 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menuapp', '0004_penjualandetail_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PenjualanDetail',
        ),
    ]
