# Generated by Django 4.2.4 on 2023-10-10 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuapp', '0009_datameja'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_meja', models.CharField(max_length=10, unique=True)),
                ('nota_sequence', models.PositiveIntegerField(default=1)),
                ('faktur_sequence', models.PositiveIntegerField(default=1)),
            ],
        ),
    ]
