# Generated by Django 4.1.7 on 2023-10-11 01:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('menuapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('manajer', 'manajer'), ('kasir', 'KASIR'), ('user', 'USER')], default='user', max_length=50)),
                ('data_meja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='menuapp.datameja')),
                ('user', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
