# Generated by Django 4.2.4 on 2023-09-10 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_userprofile_delete_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('manajer', 'manajer'), ('kasir', 'KASIR')], default='client', max_length=50),
        ),
    ]
