# Generated by Django 4.2.4 on 2023-10-10 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_userprofile_data_meja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('manajer', 'manajer'), ('kasir', 'KASIR'), ('user', 'USER')], default='user', max_length=50),
        ),
    ]
