# Generated by Django 4.2.4 on 2023-09-15 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_userprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('manajer', 'manajer'), ('kasir', 'KASIR'), ('user', 'USER')], default='kasir', max_length=50),
        ),
    ]
